import { useQuery } from "@tanstack/react-query";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { getFinancialReportById } from "#/api/financialreport.api";

interface Props {
  id: number | null;
  onClose: () => void;
}

export function ReportDetailsDialog({ id, onClose }: Props) {
  const { data } = useQuery({
    ...getFinancialReportById(id ?? 0),
    enabled: !!id,
  });

  return (
    <Dialog open={!!id} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Report Details</DialogTitle>
        </DialogHeader>

        {data && (
          <div className="space-y-3 text-sm">
            <Separator />

            <p>
              <b>Type:</b> {data.type}
            </p>
            <p>
              <b>Period:</b> {data.periodStart} → {data.periodEnd}
            </p>

            <Separator />

            <p>Revenue: {data.totalSalesRevenue}</p>
            <p>Cost: {data.totalPurchaseCost}</p>
            <p>Discounts: {data.totalDiscountGiven}</p>

            <Separator />

            <p className="font-semibold">Gross Profit: {data.grossProfit}</p>

            <p>Credit: {data.totalCreditOutstanding}</p>
            <p>Transactions: {data.totalTransactions}</p>
            <p>Units: {data.totalUnitsSold}</p>

            <Separator />

            <p className="text-muted-foreground">
              Generated by: {data.generatedBy}
            </p>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
