import { ScrollArea } from "#/components/ui/scroll-area";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "#/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "#/components/ui/table";
import { type CustomerReportDto } from "#/types/customerreport.types";
import { formatDate } from "#/utils/customerreport.utils";
import { CalendarDays, User } from "lucide-react";
import { REPORT_TYPE_META } from "./customerreport.constants";
import { ReportTypeBadge } from "./ReportTypeBadge";
import { ReportEmptyState } from "./ReportEmptyState";

interface CustomerReportDetailPanelProps {
  report: CustomerReportDto | null;
}

export function CustomerReportDetailPanel({
  report,
}: CustomerReportDetailPanelProps) {
  if (!report) {
    return (
      <div className="flex h-full items-center justify-center">
        <ReportEmptyState message="Select a report to view its details." />
      </div>
    );
  }

  const meta = REPORT_TYPE_META[report.type];

  return (
    <ScrollArea className="h-full">
      <div className="flex flex-col gap-6 p-1">
        {/* Report header card */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-start justify-between gap-4">
              <div className="flex flex-col gap-1">
                <CardTitle className="text-lg">Report #{report.id}</CardTitle>
                <CardDescription>
                  Generated on {formatDate(report.generatedAt)}
                </CardDescription>
              </div>
              <ReportTypeBadge type={report.type} />
            </div>
          </CardHeader>

          <CardContent>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
              <div className="flex flex-col gap-1">
                <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Generated By
                </p>
                <div className="flex items-center gap-1.5 text-sm">
                  <User className="h-3.5 w-3.5 text-muted-foreground" />
                  {report.generatedBy}
                </div>
              </div>

              <div className="flex flex-col gap-1">
                <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Report Type
                </p>
                <div className="flex items-center gap-1.5 text-sm">
                  {meta && (
                    <meta.icon className="h-3.5 w-3.5 text-muted-foreground" />
                  )}
                  {meta?.label ?? "Unknown"}
                </div>
              </div>

              <div className="flex flex-col gap-1">
                <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Date
                </p>
                <div className="flex items-center gap-1.5 text-sm">
                  <CalendarDays className="h-3.5 w-3.5 text-muted-foreground" />
                  {formatDate(report.generatedAt)}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Customers table */}
        {report.customers && report.customers.length > 0 && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Customers</CardTitle>
              <CardDescription>
                {report.customers.length} customer
                {report.customers.length !== 1 ? "s" : ""} in this report
              </CardDescription>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead className="text-right">Total Spent</TableHead>
                    <TableHead className="text-right">Visits</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {report.customers.map((customer) => (
                    <TableRow key={customer.id}>
                      <TableCell className="font-medium">
                        {customer.name}
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {customer.email}
                      </TableCell>
                      <TableCell className="text-right tabular-nums">
                        {customer.totalSpent != null
                          ? `$${customer.totalSpent.toFixed(2)}`
                          : "—"}
                      </TableCell>
                      <TableCell className="text-right tabular-nums">
                        {customer.visits ?? "—"}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        )}
      </div>
    </ScrollArea>
  );
}
