import { useQuery } from "@tanstack/react-query";
import { format } from "date-fns";
import {
  CalendarDays,
  Mail,
  Phone,
  User,
  TrendingUp,
  Clock,
  CreditCard,
} from "lucide-react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "#/components/ui/card";
import { Skeleton } from "#/components/ui/skeleton";
import { ScrollArea } from "#/components/ui/scroll-area";
import { Separator } from "#/components/ui/separator";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "#/components/ui/table";
import { Badge } from "#/components/ui/badge";

import { getCustomerReportById } from "#/api/customerreport.api";
import {
  CustomerReportType,
  type CustomerReportDto,
  type CustomerReportRowDto,
} from "#/types/customerreport.types";
import { ReportTypeBadge } from "./ReportTypeBadge";
import { ReportEmptyState } from "./ReportEmptyState";

interface CustomerReportDetailPanelProps {
  reportId: number | null;
}

export function CustomerReportDetailPanel({
  reportId,
}: CustomerReportDetailPanelProps) {
  const { data: report, isLoading } = useQuery({
    ...getCustomerReportById(reportId!),
    enabled: reportId !== null,
  });

  if (reportId === null) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <ReportEmptyState />
      </div>
    );
  }

  if (isLoading) {
    return <DetailSkeleton />;
  }

  if (!report) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <ReportEmptyState
          title="Report not found"
          description="This report may have been deleted or is unavailable."
        />
      </div>
    );
  }

  return <ReportDetail report={report} />;
}

function ReportDetail({ report }: { report: CustomerReportDto }) {
  const resolvedType = resolveReportType(report.type);

  return (
    <ScrollArea className="flex-1 h-full">
      <div className="p-6 space-y-6 max-w-5xl mx-auto">
        {/* Header card */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-start justify-between gap-4 flex-wrap">
              <div className="space-y-1.5">
                <div className="flex items-center gap-2 flex-wrap">
                  <CardTitle className="text-base">
                    Report #{report.id}
                  </CardTitle>
                  <ReportTypeBadge type={report.type} />
                </div>
                <CardDescription className="flex items-center gap-1">
                  <User className="h-3.5 w-3.5" />
                  Generated by {report.generatedBy}
                </CardDescription>
              </div>

              <div className="text-right text-xs text-muted-foreground space-y-0.5">
                <div className="flex items-center gap-1 justify-end">
                  <CalendarDays className="h-3.5 w-3.5" />
                  {format(new Date(report.generatedAt), "PPP")}
                </div>
                <div>{format(new Date(report.generatedAt), "p")}</div>
              </div>
            </div>
          </CardHeader>

          {(report.periodStart || report.periodEnd) && (
            <>
              <Separator />
              <CardContent className="pt-3">
                <div className="flex gap-6 text-xs">
                  {report.periodStart && (
                    <div>
                      <span className="text-muted-foreground">
                        Period Start
                      </span>
                      <p className="font-medium mt-0.5">
                        {format(new Date(report.periodStart), "PPP")}
                      </p>
                    </div>
                  )}
                  {report.periodEnd && (
                    <div>
                      <span className="text-muted-foreground">Period End</span>
                      <p className="font-medium mt-0.5">
                        {format(new Date(report.periodEnd), "PPP")}
                      </p>
                    </div>
                  )}
                  <div>
                    <span className="text-muted-foreground">Total Rows</span>
                    <p className="font-medium mt-0.5">{report.rows.length}</p>
                  </div>
                </div>
              </CardContent>
            </>
          )}
        </Card>

        {/* Rows table */}
        {report.rows.length === 0 ? (
          <ReportEmptyState
            title="No data"
            description="This report contains no rows."
          />
        ) : (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Report Data</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <ReportTable rows={report.rows} type={resolvedType} />
            </CardContent>
          </Card>
        )}
      </div>
    </ScrollArea>
  );
}

function ReportTable({
  rows,
  type,
}: {
  rows: CustomerReportRowDto[];
  type: CustomerReportType | null;
}) {
  const isPendingCredits = type === CustomerReportType.PendingCredits;
  const isTopSpenders = type === CustomerReportType.TopSpenders;

  return (
    <div className="overflow-auto">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-8 text-center">#</TableHead>
            <TableHead>Customer</TableHead>
            <TableHead>Contact</TableHead>
            <TableHead className="text-right">Total Purchases</TableHead>
            {isTopSpenders && (
              <TableHead className="text-right">Total Spent</TableHead>
            )}
            {isPendingCredits && (
              <>
                <TableHead className="text-right">Outstanding Credit</TableHead>
                <TableHead>Oldest Unpaid</TableHead>
              </>
            )}
          </TableRow>
        </TableHeader>
        <TableBody>
          {rows.map((row, idx) => (
            <TableRow key={row.customerId}>
              <TableCell className="text-center text-muted-foreground text-xs">
                {idx + 1}
              </TableCell>
              <TableCell>
                <div className="space-y-0.5">
                  <p className="font-medium text-sm">{row.fullName}</p>
                  <p className="text-xs text-muted-foreground">
                    ID #{row.customerId}
                  </p>
                </div>
              </TableCell>
              <TableCell>
                <div className="space-y-0.5">
                  <div className="flex items-center gap-1 text-xs">
                    <Mail className="h-3 w-3 text-muted-foreground" />
                    <span className="truncate max-w-[160px]">{row.email}</span>
                  </div>
                  <div className="flex items-center gap-1 text-xs text-muted-foreground">
                    <Phone className="h-3 w-3" />
                    {row.phone}
                  </div>
                </div>
              </TableCell>
              <TableCell className="text-right text-sm font-medium">
                <div className="flex items-center justify-end gap-1">
                  <TrendingUp className="h-3.5 w-3.5 text-muted-foreground" />
                  {row.totalPurchase != null
                    ? row.totalPurchase.toLocaleString()
                    : "—"}
                </div>
              </TableCell>
              {isTopSpenders && (
                <TableCell className="text-right text-sm font-semibold text-amber-600">
                  {row.totalSpent != null
                    ? `$${row.totalSpent.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
                    : "—"}
                </TableCell>
              )}
              {isPendingCredits && (
                <>
                  <TableCell className="text-right text-sm font-semibold text-rose-600">
                    <div className="flex items-center justify-end gap-1">
                      <CreditCard className="h-3.5 w-3.5" />
                      {row.outStandingCredit != null
                        ? `$${row.outStandingCredit.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
                        : "—"}
                    </div>
                  </TableCell>
                  <TableCell>
                    {row.oldestUnpaidCreditDate ? (
                      <div className="flex items-center gap-1 text-xs text-muted-foreground">
                        <Clock className="h-3 w-3" />
                        {format(
                          new Date(row.oldestUnpaidCreditDate),
                          "MMM d, yyyy",
                        )}
                      </div>
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </TableCell>
                </>
              )}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}

function DetailSkeleton() {
  return (
    <div className="flex-1 p-6 space-y-6 max-w-5xl mx-auto">
      <Skeleton className="h-28 w-full rounded-lg" />
      <Skeleton className="h-64 w-full rounded-lg" />
    </div>
  );
}

function resolveReportType(type: string): CustomerReportType | null {
  const entry = Object.entries(CustomerReportType).find(
    ([key]) => key.toLowerCase() === type.toLowerCase(),
  );
  return entry ? (entry[1] as CustomerReportType) : null;
}
