/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSignupRouteImport } from './routes/_main/signup'
import { Route as MainPartsRouteImport } from './routes/_main/parts'
import { Route as MainLoginRouteImport } from './routes/_main/login'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainTestIndexRouteImport } from './routes/_main/test/index'
import { Route as MainTestTest1RouteImport } from './routes/_main/test/test1'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSignupRoute = MainSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPartsRoute = MainPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTestIndexRoute = MainTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTestTest1Route = MainTestTest1RouteImport.update({
  id: '/test/test1',
  path: '/test/test1',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/about': typeof MainAboutRoute
  '/login': typeof MainLoginRoute
  '/parts': typeof MainPartsRoute
  '/signup': typeof MainSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/test/test1': typeof MainTestTest1Route
  '/test/': typeof MainTestIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/login': typeof MainLoginRoute
  '/parts': typeof MainPartsRoute
  '/signup': typeof MainSignupRoute
  '/': typeof MainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/test/test1': typeof MainTestTest1Route
  '/test': typeof MainTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/parts': typeof MainPartsRoute
  '/_main/signup': typeof MainSignupRoute
  '/_main/': typeof MainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_main/test/test1': typeof MainTestTest1Route
  '/_main/test/': typeof MainTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/parts'
    | '/signup'
    | '/dashboard/'
    | '/test/test1'
    | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/parts'
    | '/signup'
    | '/'
    | '/dashboard'
    | '/test/test1'
    | '/test'
  id:
    | '__root__'
    | '/_main'
    | '/_main/about'
    | '/_main/login'
    | '/_main/parts'
    | '/_main/signup'
    | '/_main/'
    | '/dashboard/'
    | '/_main/test/test1'
    | '/_main/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/signup': {
      id: '/_main/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MainSignupRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/parts': {
      id: '/_main/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof MainPartsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/test/': {
      id: '/_main/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof MainTestIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/test/test1': {
      id: '/_main/test/test1'
      path: '/test/test1'
      fullPath: '/test/test1'
      preLoaderRoute: typeof MainTestTest1RouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainLoginRoute: typeof MainLoginRoute
  MainPartsRoute: typeof MainPartsRoute
  MainSignupRoute: typeof MainSignupRoute
  MainIndexRoute: typeof MainIndexRoute
  MainTestTest1Route: typeof MainTestTest1Route
  MainTestIndexRoute: typeof MainTestIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainLoginRoute: MainLoginRoute,
  MainPartsRoute: MainPartsRoute,
  MainSignupRoute: MainSignupRoute,
  MainIndexRoute: MainIndexRoute,
  MainTestTest1Route: MainTestTest1Route,
  MainTestIndexRoute: MainTestIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
