/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as DashboardVendorsRouteImport } from './routes/dashboard/vendors'
import { Route as DashboardVehiclesRouteImport } from './routes/dashboard/vehicles'
import { Route as DashboardPartsRouteImport } from './routes/dashboard/parts'
import { Route as DashboardFinancialreportRouteImport } from './routes/dashboard/financialreport'
import { Route as DashboardCustomerreportRouteImport } from './routes/dashboard/customerreport'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as MainTestingRouteImport } from './routes/_main/testing'
import { Route as MainSignupRouteImport } from './routes/_main/signup'
import { Route as MainPartsRouteImport } from './routes/_main/parts'
import { Route as MainLoginRouteImport } from './routes/_main/login'
import { Route as MainCustomersRouteImport } from './routes/_main/customers'
import { Route as MainAboutRouteImport } from './routes/_main/about'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const DashboardVendorsRoute = DashboardVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVehiclesRoute = DashboardVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPartsRoute = DashboardPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinancialreportRoute =
  DashboardFinancialreportRouteImport.update({
    id: '/financialreport',
    path: '/financialreport',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCustomerreportRoute = DashboardCustomerreportRouteImport.update({
  id: '/customerreport',
  path: '/customerreport',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const MainTestingRoute = MainTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSignupRoute = MainSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPartsRoute = MainPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCustomersRoute = MainCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/customers': typeof MainCustomersRoute
  '/login': typeof MainLoginRoute
  '/parts': typeof MainPartsRoute
  '/signup': typeof MainSignupRoute
  '/testing': typeof MainTestingRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/dashboard/customerreport': typeof DashboardCustomerreportRoute
  '/dashboard/financialreport': typeof DashboardFinancialreportRoute
  '/dashboard/parts': typeof DashboardPartsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/customers': typeof MainCustomersRoute
  '/login': typeof MainLoginRoute
  '/parts': typeof MainPartsRoute
  '/signup': typeof MainSignupRoute
  '/testing': typeof MainTestingRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/dashboard/customerreport': typeof DashboardCustomerreportRoute
  '/dashboard/financialreport': typeof DashboardFinancialreportRoute
  '/dashboard/parts': typeof DashboardPartsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/': typeof MainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/customers': typeof MainCustomersRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/parts': typeof MainPartsRoute
  '/_main/signup': typeof MainSignupRoute
  '/_main/testing': typeof MainTestingRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/dashboard/customerreport': typeof DashboardCustomerreportRoute
  '/dashboard/financialreport': typeof DashboardFinancialreportRoute
  '/dashboard/parts': typeof DashboardPartsRoute
  '/dashboard/vehicles': typeof DashboardVehiclesRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/_main/': typeof MainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/customers'
    | '/login'
    | '/parts'
    | '/signup'
    | '/testing'
    | '/api/uploadthing'
    | '/dashboard/customerreport'
    | '/dashboard/financialreport'
    | '/dashboard/parts'
    | '/dashboard/vehicles'
    | '/dashboard/vendors'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/customers'
    | '/login'
    | '/parts'
    | '/signup'
    | '/testing'
    | '/api/uploadthing'
    | '/dashboard/customerreport'
    | '/dashboard/financialreport'
    | '/dashboard/parts'
    | '/dashboard/vehicles'
    | '/dashboard/vendors'
    | '/'
    | '/dashboard'
  id:
    | '__root__'
    | '/_main'
    | '/dashboard'
    | '/_main/about'
    | '/_main/customers'
    | '/_main/login'
    | '/_main/parts'
    | '/_main/signup'
    | '/_main/testing'
    | '/api/uploadthing'
    | '/dashboard/customerreport'
    | '/dashboard/financialreport'
    | '/dashboard/parts'
    | '/dashboard/vehicles'
    | '/dashboard/vendors'
    | '/_main/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiUploadthingRoute: typeof ApiUploadthingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/dashboard/vendors': {
      id: '/dashboard/vendors'
      path: '/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof DashboardVendorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/vehicles': {
      id: '/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof DashboardVehiclesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/parts': {
      id: '/dashboard/parts'
      path: '/parts'
      fullPath: '/dashboard/parts'
      preLoaderRoute: typeof DashboardPartsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/financialreport': {
      id: '/dashboard/financialreport'
      path: '/financialreport'
      fullPath: '/dashboard/financialreport'
      preLoaderRoute: typeof DashboardFinancialreportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/customerreport': {
      id: '/dashboard/customerreport'
      path: '/customerreport'
      fullPath: '/dashboard/customerreport'
      preLoaderRoute: typeof DashboardCustomerreportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/testing': {
      id: '/_main/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof MainTestingRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/signup': {
      id: '/_main/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MainSignupRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/parts': {
      id: '/_main/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof MainPartsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/customers': {
      id: '/_main/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof MainCustomersRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainCustomersRoute: typeof MainCustomersRoute
  MainLoginRoute: typeof MainLoginRoute
  MainPartsRoute: typeof MainPartsRoute
  MainSignupRoute: typeof MainSignupRoute
  MainTestingRoute: typeof MainTestingRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainCustomersRoute: MainCustomersRoute,
  MainLoginRoute: MainLoginRoute,
  MainPartsRoute: MainPartsRoute,
  MainSignupRoute: MainSignupRoute,
  MainTestingRoute: MainTestingRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardCustomerreportRoute: typeof DashboardCustomerreportRoute
  DashboardFinancialreportRoute: typeof DashboardFinancialreportRoute
  DashboardPartsRoute: typeof DashboardPartsRoute
  DashboardVehiclesRoute: typeof DashboardVehiclesRoute
  DashboardVendorsRoute: typeof DashboardVendorsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCustomerreportRoute: DashboardCustomerreportRoute,
  DashboardFinancialreportRoute: DashboardFinancialreportRoute,
  DashboardPartsRoute: DashboardPartsRoute,
  DashboardVehiclesRoute: DashboardVehiclesRoute,
  DashboardVendorsRoute: DashboardVendorsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiUploadthingRoute: ApiUploadthingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
